#Owned by DairyMan@Whirlpool
#
#Copyright GNU act.
include $(TOPDIR)/rules.mk

PKG_NAME:=ext-custom-level316
PKG_VERSION:=1.000
PKG_RELEASE:=1

PKG_MAINTAINER:=Created by DM/makefile by Cobia@whirlpool
include $(INCLUDE_DIR)/package.mk

define Package/ext-custom-level316
  SECTION:=utils
  CATEGORY:=ROOter
  SUBMENU:=CustomBuilds16
  DEPENDS:=+ext-custom-level3 +build-mwan3
  TITLE:=Level3 Build packages with MWan3
  PKGARCH:=all
endef

define Package/ext-custom-level316/description
  Level3 Build packages with MWan3
endef


define Build/Compile
endef

$(eval $(call BuildPackage,ext-custom-level316))
