#!/bin/sh /etc/rc.common
. /lib/functions.sh
# Copyright (C) 2006 OpenWrt.org

START=91

start() {
	if [ -e /etc/crontabs/root ]; then
		sed -i '/flash.sh/d' /etc/crontabs/root
	fi
	tim=$(uci -q get flash.flash.time)
	HOUR=${tim:0:2}
	MIN=${tim:3:2}
	rand=$(uci -q get flash.flash.random)
	if [ "rand" = '0' ]; then
		RANDOM=$(date +%s%N | cut -b10-19)
		range=$(( $RANDOM % 45 + 0 ))
		let MIN=$MIN+$range
		if [ "$MIN" -gt 59 ]; then
			let MIN=$MIN-60
			let HOUR=$HOUR+1
		fi
	fi
	echo "$MIN $HOUR * * * /usr/lib/flash/flash.sh &" >> /etc/crontabs/root
	/etc/init.d/cron restart
}