#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=88
USE_PROCD=1

log() {
	logger -t "SCAN RUNNING" "$@"
}

start_service()
{
	uci set bandscan.info.running="0"
	uci set bandscan.info.stopping="0"
	uci commit bandscan
	log "Stop Running Flag:"
}
