#!/bin/sh /etc/rc.common
# Copyright (C) 2012-2014 OpenWrt.org

START=90

USE_PROCD=1
PROG="/usr/sbin/easycwmpd"

UCI_SET="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set"
UCI_GET="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} get"
UCI_COMMIT="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} commit"
init_device_info() {
	local val oval
	local change=0

	if [ -e /etc/custom ]; then
		lua /usr/lib/rooter/customname.lua
	fi
	val=$(cat /tmp/sysinfo/model)
	oval=`$UCI_GET easycwmp.@device[0].hardware_version`
	[ -n "$val" -a "$val" != "$oval" ] && { $UCI_SET easycwmp.@device[0].hardware_version="$val"; change=1; }

	source /etc/codename
	val=$CODENAME
	oval=`$UCI_GET easycwmp.@device[0].software_version`
	$UCI_SET easycwmp.@device[0].software_version="$val"; change=1
	
	#The same thing here for OUI and SerialNumber
	local sf="/tmp/es.secret"
	serial-idtool -i generate "$sf" > /dev/null
	secret="$(cat $sf)"
	rm "$sf"
	serial=${secret:0:10}
	oval=`$UCI_GET easycwmp.@device[0].serial_number`
	[ -n "$serial" -a -z "$oval" ] && { $UCI_SET easycwmp.@device[0].serial_number="$serial"; change=1; }
	
	OUI="C0FFEE"
	oval=`$UCI_GET easycwmp.@device[0].oui`
	[ -n "$OUI" -a "$OUI" != "$oval" ] && { $UCI_SET easycwmp.@device[0].oui="$OUI"; change=1; }


	[ "$change" = "1" ] && $UCI_COMMIT easycwmp
}

start_service() {
	local enable=`uci -q get easycwmp.@local[0].enable`
	if [ "$enable" == "1" ]; then
		init_device_info
		procd_open_instance
		procd_set_param command "$PROG" -f
		if [ "$1" = "--boot" ];then
			procd_append_param command --boot
		else
			procd_append_param command --getrpcmethod
		fi
		procd_set_param respawn "3" "7" "0"
		procd_close_instance
	fi
}

boot() {
	start --boot
}

service_triggers()
{
	procd_add_reload_trigger easycwmp
}
