#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=19

start() {
	i=488
	echo $i > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio${i}/direction
	echo 1  > /sys/class/gpio/gpio${i}/value
	sleep 2
	echo 0 > /sys/class/gpio/gpio${i}/value
	sleep 10
}
