#!/bin/sh

uci set system.@system[0].hostname='AlwayWireless'
uci commit system
/etc/init.d/system restart

uci set dhcp.lan.force='1'
uci commit dhcp
/etc/init.d/dnsmasq restart

uci set wireless.radio0.txpower='23'
uci set wireless.radio0.txpower='23'
uci commit wireless
wifi up

uci set firewall.@defaults[-1].flow_offloading='1'
uci set firewall.@defaults[-1].flow_offloading_hw='0'
uci commit firewall
/etc/init.d/firewall restart